### ISSUE TITLE
Join forces with Metagame and GotchiGaang to form MSG-13

### ISSUE THREAD

**Issue by chair28980** [ShenaniganDApp/SHEiP#10]
SHEiP: 
title: Join forces with Metagame and GotchiGaang to form MSG-13
author: Chair Trees @chair28980 
discussions-to:
status: Draft
category: Meta
type: Operations
created: 2021-08-05
edited: 

## Simple Summary

The great and venerable @musashi13 has been building the GotchiGaang Discord server through his ambassadorship. https://discord.gg/qvCRWt2v

The topic of Aavegotchi, and its supporters has also infected MetaGame, another community that is heavily cross populated with Shenanigan Sheiites.

With the increasing popularity of Aavegotchi, and the massive potential for the Realm ecosystem (coming soom) the idea has sprouted to join forces and create and alliance with Metagame + SHE + GotchiGaang = MSG-13.

Musashi's awesome Notion doc: https://musashi13.notion.site/musashi13/MetaGame-Gotchigaang-Mayne-b480b96f0499416d808fe50f406e7d3f

How to play Aavegotchi: https://hackmd.io/0unenTCYTUWm1kUeY8KMyQ?view

Metaverse Wiki: https://wiki.aavegotchi.com/en/metaverse

## Abstract

High Level: Three communities paartner to create MSG-13 alliance. Strategies to obtain a Paarcel within the Realm will be employed. These strategies are numerous and are too large in scope to fully list here but include:
- Becoming a Paartner and obtaining a Paartner Paarcel
- Creating a pool/multisig and pooling funds for raffles and auctions

Aavegotchi has continued to be at the forefront of most all things blockchain. They have a phenomenal team and a highly addictive product both in design and functionality. They have been leading innovation in the DeFi, NFT, Gamified Finance, L2 solutions, and blockchain space as a whole.

The visibility and marketing potential of having a Paartner Parcel, along with the community effect and broader outreach make it a 0 brainer.

Very broadly, the MSG-13 alliance will give us more power to:
a) Propose a partnership to Aavegotchi (giving us a partner paarcel in the citadel, more on this below)
b) Work together as a team/guild to further community bonding, and profit
c) Coordinate complex Alchemica Mining strategies
d) Perform other classic Guild functions

## Motivation

Game Night has been a success in its first iteration, it created a good network effect, the NFT trophies were a hit. Since the break we have been searching for a good next step to evolve.

## Specification

- Create cross discord server channel between the MSG-13 servers.
- Create rules, guidelines and standards to be determined in the future.
- Create a minigame (the SugaarPaacketsPaass game has been fully wireframed and is ready for development) please ask me (chair) if you want to see the wireframe I will give a demo!

## Rationale

The Gotchi machine is just getting started, the ecosystem is supported by both savvy long time eth holders and new blood players less interested in smart contracts and more interested in cute digital pets, and this is before the expansion into the Realm.

The network effect of Aavegotchi is massive, with Minigames and the upcoming Liquidator invasion, it is ripe for harvesting even more granular games within the community, given that all the data is on chain and queryable.

## Backwards Compatibility

yes

## Implementation

 
Should be carried out in phases, beginning with reaching full consensus from all involved parties.

A council of representatives should be created to rep their respective camps. Due to much cross community pollination it will be important to have one (or two) firm reps for each individual camp to have a clear voice and perspective from each.

## Security Considerations

- Cred farmers
- Players using the information gained from the MSG-13 playbooks can use this knowledge against us

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by duckcmdr** [comment]
What's a Paartner Paarcel?

**Comment by chair28980** [comment]
@duckcmdr ![image](https://user-images.githubusercontent.com/29414216/128390196-b5a8e341-1b5a-4d12-938b-e39dd421594a.png)

![image](https://user-images.githubusercontent.com/29414216/128436689-97513f69-4e1d-45c0-80d4-4684f49d7c6a.png)

![image](https://user-images.githubusercontent.com/29414216/128436711-0a0afad0-ed88-4007-8289-b11cd14b496f.png)

Sauce: https://docs.google.com/document/d/1hUHF29F3_tByWd8ezSphYEE0gPJYg3K5CN1K-X3_WK8/mobilebasic#heading=h.diix7kqkl8ck

**Comment by youngkidwarrior** [comment]
Aavegotchi is an awesome project. Shenanigan utilizes a lot of similar technology and I truly believe they are leading the space in innovation.

Pairing with other great projects like MetaGame and Aavegotchi is a power move for SHE.

I still have a bit of hesitation:

- How much does aavegotchi require for a paarcel? What is the price point for SHE?

- @chair28980 will you be the Shenanigan representative. If we pool resources, I'd like to be assured SHE is fairly represented in the paarcel. Has gotchigaang setup a weekly meeting or newsletter where I can learn more about what is happening each week?

- Do gotchis have anything to do with helping athletes? I understand aavegotchi is really amazing, but how can we tie this in to the SHE narrative? I'm not convinced it is productive to extend our reach into areas that have little to do with non-athletics.

These are all my concerns. I think overall I support our community reaching into other communities. Interoperability is a  powerful tool. I like the idea presented.

**Comment by chair28980** [comment]
@youngkidwarrior 

1. Paarcels can be acquired three different ways. Becoming a Paartner (the golden goal of MSG-13), winning a raffle and winning an auction respectively. I am working on figures now, as well as how the resources might be pooled together.

2. I am very willing to be one of the representatives (I think we will need 2 per team/click, so six reps total)

- One of our first orders of business is to setup a cross community discord channel, once we have confirmation from all involved parties that we are moving forward.

3. Re: Gotchis and athletes, this is a good point for me to think about further, I don't have a great answer at the moment but I will be thinking about this.

**Comment by Musashi13** [comment]
> @chair 
> 
>     1. Paarcels can be acquired three different ways. Becoming a Paartner (the golden goal of MSG-13), winning a raffle and winning an auction respectively. I am working on figures now, as well as how the resources might be pooled together.
> 
>     2. I am very willing to be one of the representatives (I think we will need 2 per team/click, so six reps total)
> 
> 
>     * One of our first orders of business is to setup a cross community discord channel, once we have confirmation from all involved parties that we are moving forward.
> 
> 
>     1. Re: Gotchis and athletes, this is a good point for me to think about further, I don't have a great answer at the moment but I will be thinking about this.

- There could be a betting dApp deployed for betting on the outcome of aarena battles.
- Gotchi **Aathletes** (**Gaathletes?**) could post **Challenges/Matter**  eg *I will attack this Aavegotchi and win* and other Gotchis and lickuidators could place their **Bets/Charges Matter with Ions, Particles**

**Comment by chair28980** [comment]
Gonna close this out to de-clutter. MSG is live and in action. Yeet.
