### ISSUE TITLE
Flow with SHE

### ISSUE THREAD

**Issue by rlholmes38** [ShenaniganDApp/SHEiP#15]
---
SHEiP: 4
title: Flow with SHE
author: Rachel Holmes, @rlholmes38 (MetaSpace), holmeshealing.com 
status: Last Call
category: Standards
type: Community
created: 2022-02-14
edited: 2022-03-04
requires: 
replaces: 
---

## Simple Summary

A weekly yoga flow class with complimentary published content

## Abstract

Each week we will provide a yoga flow class via zoom. To encourage participation, each class will be recorded so that people can take the class when it best suites their schedule. We will have content published in SHE's substack that will correspond to the themes we are exploring each quarter and month, and that coincide with the practice we do in the class. This a great way to distribute the token throughout the community, and to distinguish which community members are active.

## Motivation

We want to get our community moving, connected to their bodies, and do something that is mindful and compliments their current practices. This will also help the DAO align with its values, and provide an event that will allow the DAO to grow in its mission.

### Minimum Viable Contributions
- 60 minute live yoga class via zoom
- Recording of the live session
- attendance will be taken and documented

### Bonus Contributions
- Articles related to the themes and what we are focusing on in the yoga class
- Athlete specific focused meetings

The yoga classes will be added to the [Flow with SHE Repo](https://github.com/rlholmes38/Flow-with-SHE) where I will be submitting the weekly contributions to be reviewed. If this proposal passes, this repo will be forked and merged into the SHE github organization where it will added to the sourcecred graph.

Cred Allotment
- Instructor MVC rate (minimum viable contribution)
16 cred 
- Participant Rate via an initiative
1 cred

In addition to the contribution cred, bonus cred will be allotted per live person at a rate of .2 cred. 

## Rationale

We decided to format the class this way for three reasons.
- Providing a recorded class provides more people the ability to take the class, and feel a part of the community.
- Having written content helps connect the right and left brain. The content will help people understand  intellectually, while the exploring the movement we understand it in our bodies. 
- Token incentives will introduce new people to the DAO through movement while also getting new people to do yoga.

## Backwards Compatibility

There are no backwards compatibilities.

## Implementation

- Taking time to plan and implement a yoga class each week: about two hours.
- Creating quarterly themes, and content around those themes for deeper understanding. 
- Make myself available for any athlete specific meetings as they come.

**Comment by cheo0202** [comment]
great idea guys we need spaces for interaction, meeting for the community

**Comment by diegoleal8802** [comment]
👏👏👏👏
great initiative. There should be more stuff like this. like karate dance....

**Comment by MariaEstrada07** [comment]
Excellent, I loved your idea, begging you to pass your proposal to be present 🙌

**Comment by clna2402** [comment]
excellent initiative. count me in

**Comment by romel33** [comment]
good idea

**Comment by coro4103** [comment]
Excellent opportunity I would like to participate count on me 🤗🤗🤗🤗👍👌

**Comment by youngkidwarrior** [comment]
@rlholmes38 
This proposal seems like a great initiative for the SHE community to support. The Cred weights feel fair when compared to the weight of code contributions/discord etc.

I also find the contributions easy to follow and don't see a problem reviewing them in the future as they are. 


I've moved this into Last Call and I am excited to sign off on this and move it into the Final stage.

Next steps are for you to turn this into a Pull Request and then we will make the vote on Snapshot
