### ISSUE TITLE
Actualizar las herramientas de información en la D

### ISSUE THREAD

**Issue by FOLLOWSHE** [ShenaniganDApp/SHEiP#21]
---
SHEiP: <to be assigned>
title: <SHEiP title>Actualizar las herramientas de información en la D
author: José Coronado (cheo0202)
status: Idea
category: Informational
type: Design
created: 2022-03-24T13:58:14Z
edited: N/A
requires: To be determined
replaces: To be determined
---

## Simple Summary

Las guías y la información de ser parte de SHE. No están actualizadas.

## Abstract

Hay que tomas la información de cómo ingresar a she y contribuir. Actualizar para que los nuevos miembros las usen como herramientas de guía.

## Motivation

Hace poco entro una chica y yo le pase las guías para que se ayudará cuando. Me di cuenta no le funcionaban porque ahora hay diferentes pasos para le verificación

## Specification

La idea es crear guías. Nuevas.

## Rationale

Manteniendo estás herramientas actualizadas podemos hacer que las personas entren y sigan los pasas más cómodas

## Backwards Compatibility

To be determined

## Security Considerations

To be determined

**Comment by youngkidwarrior** [comment]
English please!
