### ISSUE TITLE
Community Vote for PANTS Design

### ISSUE THREAD

**Issue by malikvprice** [ShenaniganDApp/SHEiP#4]
---
SHEiP: <to be assigned> 
title: <SHEiP title> Vote for PANTS Design
author: @malikvprice @duckcmdr 
discussions-to:
status:  Last Call
category: Standards
type: Design
created:  2021-07-27
edited: 2021-09-23
---

## Simple Summary

Community vote on the style of PANTS to be fabricated for our [Pants.energy](url) NFT. 

## Abstract

We are at the final stage of our sprint to release our first edition of NFT-backed activewear. There are two design prototypes to choose from. We are conducting a community vote via this SHEiP. This is purely a personal preference based on what you would like to wear. Pick which one you would like best by commenting below.

## Motivation

Our goal is to bring PANTS to the Shenanigan community and provide a system of governance in regards to which design style our users prefer as a collective.

## Specification

Made with a 95% polyester and 5% spandex blend. Each panel is individually printed, cut, and sewn to ensure a flawless graphic with no imperfections. Sizes range from extra small to four extra-large (XS-4XL). 

Delivery time is 4-6 weeks, with rush delivery available for an additional $8/pair. 

## Rationale

1. Give the community a voice in this milestone decision.
2. Utilize the SHEiP protocol to aggregate consensus and execute decision.

## Implementation

✅ Stage 1: Developed front end at [Pants.energy](url). Airdropped PANTS tokens to all prior SHWEATPANTS holders. Stood up liquidity from DAO treasury to match SHWEATPANTS token value as of May 26 snapshot.

✅ Stage 2: Merged PANTS token and logo with Honeyswap official token list.

✅ Stage 3: Team collaborated with our designer/distributor to develop two PANTS designs.

✅ Stage 4: Designer fabricated and delivered two working PANTS prototypes (one of each design).

➡ Stage 5: Community vote between PANTS designs.

_Prototype 1_ 
![image](https://user-images.githubusercontent.com/67035793/134421153-46dbd7a4-77e2-4b0f-beb7-13c2e36439fe.png)
_Prototype 2_ 
![image](https://user-images.githubusercontent.com/67035793/134271136-5806ca7d-883c-43e6-9158-fdf7d8b8a069.png)

Vote will be held on snapshot in the upcoming week

## Security Considerations

There are no security considerations.

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by youngkidwarrior** [comment]
@malikvprice 
 I like the initiative you took making this proposal. Giving others a voice is the very first step in a DAO

Can I learn more about the distributors you found? Link to their website, examples of products, how reputable are they, etc
Do you mind adding a few links to the proposal?

**Comment by chair28980** [comment]
I lean Joggers for the more modern look. Would be interested in the difference in look if thats available.

Either way, still more useful than socks.

**Comment by Jega71** [comment]
What a thing, I'm going for the Joggers, a more rebellious spirit.

**Comment by cheo0202** [comment]
joggers are in fashion. it will be a good to option

**Comment by MariaEstrada07** [comment]
I like joggers better, it is a casual and fresh style

**Comment by lofimaster** [comment]
joggers

**Comment by Musashi13** [comment]
Joggers fa sho!

**Comment by kittyslasher** [comment]
I vote for Joggers all the way!

**Comment by Itzamna420** [comment]
Prototype 1

**Comment by MariaEstrada07** [comment]
Amazing , loved the prototype 1

**Comment by Jega71** [comment]
Prototype 1

**Comment by duckcmdr** [comment]
To alleviate confusion, I cleaned up some of the older comments from July, back when this SHEiP draft was set up to discuss the style of fabric used for PANTS.

**Comment by coro4103** [comment]
I like the second design of the pants

**Comment by chair28980** [comment]
2

**Comment by NoheliaSHE** [comment]
2

**Comment by diegoleal8802** [comment]
Prototype 1

**Comment by clna2402** [comment]
Prototipo 1

**Comment by TheShosu** [comment]
The 1
