### ISSUE TITLE
Reduce SourceCred's tithe to .05%

### ISSUE THREAD

**Issue by youngkidwarrior** [ShenaniganDApp/SHEiP#6]
---
SHEiP: <to be assigned>
title: Reduce SourceCred's tithe to .05%
author: Victor Ginelli @youngkidwarrior 
discussions-to: <URL of the Github issue for this SHEiP (if this is a PR)>
status: Draft
category: Informational
type: Operations
created: 2021-07-30
edited: <date created on, in ISO 8601 (yyyy-mm-dd) format>
requires: N/A
replaces: N/A
---

## Simple Summary

Reduce Tithing to SourceCred from 5% to .05%

## Abstract

SourceCred currently receives 5% of all Cred SHE produces since it begun using SourceCred. Back in April 2021, SourceCred launched a new algorithm called `CredRank` which launched settings to allow for Cred dependency time periods. We can now adjust the SourceCred tithing to be .05% starting April 1st 2021. This shows the power of SourceCred, as the system will adjust our weekly distirbution until it matches this newly defined token state.  I propose a move to .05% tithing to SourceCred for the time being.

## Motivation

5% is a large amount of the PRTCLE token. It's double the amount we give back to the DAO. As it stands now, those tokens just sit there in SourceCred's wallet. SourceCred is currently the 5th highest Cred earner on the [scoreboard](http://she.energy/scoreboard). I believe this is a much fairer amount at PRTCLEs current status.

## Rationale

This proposal is heavily inspired from MetaGame, which [also reduced its tithing on April 1st 2021](https://github.com/MetaFam/XP/blob/9f095ca2c429d47fed07d3a046e704f31d3fd3ea/config/dependencies.json#L12) from 5% to .05% 

## Implementation

Add a new `period` in `scoreboard/config/dependencies.json`
```javascript
[
    {
        "autoActivateOnIdentityCreation": true,
        "id": "y2DEs8VNZNcol8PiD8QUKA",
        "name": "sourcecred",
        "periods": [
            {
                "startTime": "2020-09-20",
                "weight": 0.05
            },
            {
                "startTime": "2021-04-1",
                "weight": 0.005
            }
        ]
    },
    {
        "autoActivateOnIdentityCreation": true,
        "id": "YJFlIJaywRBz6Pgkqg0ZSg",
        "name": "SHE",
        "periods": [
            {
                "startTime": "2020-01-10T08:45:34.676Z",
                "weight": 0.025
            }
        ]
    }
]
```

## Security Considerations

It might be poignant to ask MetaGame and SourceCred why they reached this number and if it feels fair. SOurceCred had originally asked for 5%, which I felt was unfair at the time. I didn't mind, however, as SourceCred deserved a lot fro their work and I understood that `CredRank` was coming, meaning the value could be adjusted. Before we make changes, we should ask them what they think is fair.

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by cheo0202** [comment]
it's okay to reduce the amount.

**Comment by Joseignacio1996** [comment]
igual estoy de acuerdo con la propuesta.

**Comment by MariaEstrada07** [comment]
I agree

**Comment by Jega71** [comment]
Necessary and fair.

**Comment by NoheliaSHE** [comment]
Yes, agree anything to improve SHE

**Comment by llealg2** [comment]
yes, option 1 excellent

**Comment by coro4103** [comment]
Option 1

**Comment by kittyslasher** [comment]
I agree with the reduction of percentage going to source cred. I however believe the remaining 4.5% or remaining balance after discussing with source cred should be reallocated to the DAO

**Comment by Yuviry** [comment]
Option 1

**Comment by Jolie-Ze** [comment]
seems fair to me.

is there a projection of where sourcecred will be on your ledger after the change? (instead of 5th?) asking out of curiosity

**Comment by AL0YSI0US** [comment]
> I agree with the reduction of percentage going to source cred. I however believe the remaining 4.5% or remaining balance after discussing with source cred should be reallocated to the DAO

Re: Reallocating the remaining balance to the DAO 

Is this suggestion implying that the tithing being lowered (seen as less valuable of a contribution or has too much stake in the token collective) and that the funding that is with sourcecred be taken from SC community and transferred to the metacred DAO.

I'm not sure if I'm interpreting this thread correctly. 

I have no opinion on the tithing reduction sans I think it's a dramatic change in general percentage wise just as far as numbers are considered. But that's only looking at the numbers alone not the impact. 

Curious why @youngkidwarrior  felt 5% seemed and still seems unreasonable. I'm asking these questions to understand not to play devil's advocate or poke a bear. I'm genuinely curious about the decision points and curiosities  we come to in these spaces.

**Comment by Jolie-Ze** [comment]
> > I agree with the reduction of percentage going to source cred. I however believe the remaining 4.5% or remaining balance after discussing with source cred should be reallocated to the DAO
> 
> Re: Reallocating the remaining balance to the DAO 
> 
> Is this suggestion implying that the tithing being lowered (seen as less valuable of a contribution or has too much stake in the token collective) and that the funding that is with sourcecred be taken from SC community and transferred to the metacred DAO.
> 
My read is that the remaining tithe is usurped into the SHE community.

**Comment by youngkidwarrior** [comment]
@AL0YSI0US It is exactly as you state,

I feel 5% of the total Cred supply is very high cost for using SourceCred, at least at the current time of SourceCred's lifespan. For example, the Shenanigan DAO itself is only given 2.5% of the total Cred. None of SourceCred's existing PRTCLE would be lost/taken by SHE.

@Jolie-Ze is right, the Cred would go back into the community. I believe the current soft consensus is the DAO needs a higher tithe than 2.5%, so it could likely be used for that.

I'm curious to hear more of SourceCred;s feelings towards this before I make a decision, which is why I invited you all to the conversation. Only after I saw MetaGame's change in tithe do I feel comfortable bringing this up as a discussion.

**Comment by AL0YSI0US** [comment]
@youngkidwarrior thank you for the context. I too am curious what other members within sourcecred think as well. 

I'll see if I can get some more 👀's on your proposal. Appreciating your labor and attention to detail.

**Comment by AL0YSI0US** [comment]
Many eyes have seen your proposal

> . . . and the crickets
>
> . . . my how they chirp. 🦗 

🤷🏾‍♂️ I'm not sure what to make of this. 
🎬  I guess the show goes on eh?

With no clear opposition do you intend to lower the tithing from 5% to .05%?
