### ISSUE TITLE
Join POOLHaus

### ISSUE THREAD

**Issue by youngkidwarrior** [ShenaniganDApp/SHEiP#7]
---
SHEiP: <to be assigned>
title: Join POOLHaus
author:  Victor Ginelli (@youngkidwarrior )
discussions-to: <URL of the Github issue for this SHEiP (if this is a PR)>
status: Draft 
category: Informational
type: Operations
created: 2021-07-30
edited: 2021-08-03
requires: N/A
replaces: N/A
---

## Simple Summary

Join [PoolHAUS](https://medium.com/daohaus-club/poolhaus-and-decentralised-liquidity-provision-ced87ffe656) , a DAO organized by our DAO provider [DAOHaus](http://daohaus.gg) 

## Abstract

PoolHAUS is a DAO made to encourage liquidity within the DaoHaus/UberHaus community on HAUS token. In return for locking LP tokens in the DAO for 3 months, DAO members will receive HAUS rewards based on the magnitude of their stake. PoolHAUS will be opening its doors to the public until August 7th. Minimum contribution is 10 HAUS/WETH LP Tokens *or* 1.5 xDai WETH.

## Motivation

Since we are staying on xDai for the foreseeable future, supporting the xDai community should be part of
 SHE's backbone. With our upcoming application to UberHaus, we can show further support for our DAO platform by pledging some of the treasury to the HAUS token At the same time, we will be receiving HAUS in return for our support, which is a win-win if we are bullish on the state of HAUS token. 

Here are the reward allocation from the article:

> - Over the 3 month period, 2500 HAUS will be issued to PoolHAUS, these rewards will be distributed proportionally based on contributions. These rewards can also be increased by UberHaus if decided by the DAO.
> - WETH contributors to PoolHAUS are given higher rewards than LP contributors; an additional 825 HAUS will be distributed pro-rata.
> - These additional rewards will be airdropped to WETH contributors at the end of PoolHAUS.

## Rationale

This is the first Iteration of PoolHaus. Participating could lead to more collaborations between HAUS and PRTCLE in the future. DAOHaus has built a great platform and given an opportunity to mutually benefit between our DAO

## Implementation

Here are the requirements from the article:

> - Contributors will pledge a minimum of 10 WETH/HAUS LP tokens from Swapr, or 1.5 WETH to the DAO. Every 100 DAO shares (Loot or Gov) will represent 1 WETH/HAUS LP token or 0.15 ETH.
> - Contributions will be open for a one week window; During which LP tokens & ETH contributions will be pegged at the start of the PoolHAUS contribution window.
> - PoolHAUS will hold its LP position in the minion for 3 months, meaning contributors won’t be able to Ragequit (claim) their LP tokens back from the DAO before this 3 month period ends (Unless otherwise voted by the DAO).

It seems as though a community member @yalormewn is willing to donate their HAUS tokens to this cause, with promise of returned reward at the end of the 3 months. The max Shenanigan can afford to match with is 25,000 DAI, or ~1565.92 HAUS (at time of writing). This opens up more options for SHE

There are a few monetary options. It makes sense to pledge LP Tokens since an extra 825 HAUS will be given to LP pledgers over WETH pledgers
0. Don't pledge to POOLHaus
1. Pledge the minimum 10 LP Tokens (no community)
2. Pledge $10,000 worth of LP Tokens (no community)
3. Match 1k Haus from Yalor (currently $16651.2) with WETH

Option 0 - No pledge
Option 1 - will provide very little reward at the minimum but it is very safe
Option 2 - gives decent rewards and allows SHE to keep everything that is earned,
Option 3 - gives biggest rewards by allowing SHE to utilize Yalor's HAUS pledge, but also requires the largest risk from SHE

We will use a gnosis multisig on xdai controlled by SHE Core to pledge the DAO, since a DAO vote will take too long to make the 1 week pledge window. We will have use blockscout to make sure Yalor gets his fair share of rewards back at the end of the 3 months.

## Security Considerations

Using a Gnosis safe should make the shares secure.

If we are not feeling bullish on HAUS/xDai, then this would not be smart. We should probably consider a migration to another chain if we don't feel this is a good move. We are wasting time on xDai if we are not open to collaborating with other xDai projects.

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by cheo0202** [comment]
I believe in option 1. It is more available to everyone.

**Comment by YalorMewn** [comment]
Let's do it, option 2 has my support 🥈 I believe poolHAUS will bring a wave of new incentives into the ecosystem.

**Comment by MariaEstrada07** [comment]
Thinking about me and the new users would be better option 1, it is more accessible to everyone

**Comment by Jega71** [comment]
All my support for option 2. I like this, collaborations are an important item for healthy growth. "" Something must be invested to win "" there is no other logical way.

**Comment by NoheliaSHE** [comment]
I lean towards option number 1

**Comment by llealg2** [comment]
option 1 excellent

**Comment by coro4103** [comment]
Option 1

**Comment by kittyslasher** [comment]
I am willing to pledge all my current Haus holding for option 3. If we cant pull the funds for option 3. If 3 is not an option then I will go with option 2 as it will be the next best choice

**Comment by YalorMewn** [comment]
I can pledge 5k of HAUS if the community wants to match me, just need to clarify what the repayment schedule is going to be 🤑

**Comment by chair28980** [comment]
As a hodler of haus i too am willing to pledge in that scenario. 

In general though i support the fastest and easiest option we can facilitate to bolster liq and stabilize the pewls.

**Comment by youngkidwarrior** [comment]
@YalorMewn @kittyslasher @chair28980 
Pooling our HAUS is a good idea. I don't think we have the bankroll to match 5k+ HAUS though. That is $140,000 worth of liquidity!

I'd say our max right now is $50,000 total WETH/HAUS LP, which is $25k from Shenanigan. 

I'm not sure what a repayment schedule looks like. I can ensure that the we can make a proposal for it. What are you looking for @YalorMewn ?

**Comment by YalorMewn** [comment]
Well I am looking to place my HAUS in service of the community, not to donate it. So I would place up to 1000 HAUS into a pool that would need to be returned to me at a future date, perhaps when the pool is closed or at some depth of liquidity, idk exactly

What rewards are going to be in place for LP's ?

**Comment by youngkidwarrior** [comment]
@YalorMewn ah, I thought that seemed generous 

Yes, we'd definitely pay you back the HAUS you pledged. Here is the quote from the POOLHaus article

> - Over the 3 month period, 2500 HAUS will be issued to PoolHAUS, these rewards will be distributed proportionally based on contributions. These rewards can also be increased by UberHaus if decided by the DAO.

> - WETH contributors to PoolHAUS are given higher rewards than LP contributors; an additional 825 HAUS will be distributed pro-ratae
 >- These additional rewards will be airdropped to WETH contributors at the end of PoolHAUS

**Comment by YalorMewn** [comment]
Here is a suggestion, what if we take 1k HAUS ( provided by me) and the community matches with equal WETH, then we split the fees earned, whenever the pool closes we just send the prospective amounts back to the depositor, that is if it's a 50/50 pool ?

**Comment by youngkidwarrior** [comment]
I like this idea. I will update the proposal accordingly
